version: '3.3'
services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=post123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres+psycopg2://postgres:post123@db:5432/testdb
    depends_on:
      - db
